interpolate:
  convergence_2d_from:
    Isothermal: false
    IsothermalSph: true
  deflections_yx_2d_from:
    Isothermal: false
    IsothermalSph: true
  image_2d_from:
    sersic: false
    sersicSph: true
  potential_2d_from:
    Isothermal: false
    IsothermalSph: true
# Certain light and mass profile calculations become ill defined at (0.0, 0.0) or close to this value. This can lead
# to numerical issues in the calculation of the profile, for example a np.nan may arise, crashing the code. 
  
# To avoid this, we set a minimum value for the radial coordinate of the profile. If the radial coordinate is below 
# this value, it is rounded up to this value. This ensures that the profile cannot receive a radial coordinate of 0.0.

# For example, if an input grid coordinate has a radial coordinate of 1e-12, for most profiles this will be rounded up
# to radial_minimum=1e-08. This is a small enough value that it should not impact the results of the profile calculation.

radial_minimum:
  radial_minimum:
    MockGridRadialMinimum: 2.5
    MockIsothermal: 0.0001
    MockIsothermalSph: 0.03
    Chameleon: 0.0001
    ChameleonSph: 0.0001
    DevVaucouleurs: 0.0001
    DevVaucouleursSph: 0.0001
    ExponentialGradient: 0.0001
    ElsonFreeFall: 0.0001
    ElsonFreeFallSph: 0.0001
    Exponential: 0.0001
    ExponentialCore: 0.0001
    ExponentialCoreSph: 0.0001
    ExponentialSph: 0.0001
    ExternalShear: 0.0001
    Gaussian: 0.0001
    GaussianSph: 0.0001
    gNFW: 0.0001
    gNFWMCRLudlow: 0.0001
    gNFWSph: 0.0001
    Isothermal: 0.0001
    IsothermalCore: 0.0001
    IsothermalCoreSph: 0.0001
    IsothermalSph: 0.0001
    MassSheet: 0.0001
    Moffat: 0.0001
    MoffatSph: 0.0001
    NFW: 0.0001
    NFWMCRDuffySph: 0.0001
    NFWMCRLudlow: 0.0001
    NFWMCRLudlowSph: 0.0001
    NFWMCRScatterLudlow: 0.0001
    NFWMCRScatterLudlowSph: 0.0001
    NFWSph: 0.0001
    NFWTruncatedMCRDuffySph: 0.0001
    NFWTruncatedMCRLudlowSph: 0.0001
    NFWTruncatedMCRScatterLudlowSph: 0.0001
    NFWTruncatedSph: 0.0001
    PointMass: 0.0001
    PowerLaw: 0.0001
    PowerLawBroken: 0.0001
    PowerLawBrokenSph: 0.0001
    PowerLawCore: 0.0001
    PowerLawCoreSph: 0.0001
    PowerLawSph: 0.0001
    Sersic: 0.0001
    SersicCore: 0.0001
    SersicCoreSph: 0.0001
    SersicGradient: 0.0001
    SersicSph: 0.0001
    ExponentialGradientSph: 0.0001
    SersicGradientSph: 0.0001
    EllProfile: 0.0001
    SersicAdaptTest: 0.0001


# Over sampling is an important numerical technique, whereby light profiles images are evaluated on a higher resolution
# grid than the image data to ensure the calculation is accurate.

# By default, a user does not specify the over sampling factor, and a default over sampling scheme is used for each
# profile. This scheme first goes to the centre of the profile, and computes circles with certain radial values
# (e.g. radii). It then assigns an over sampling `sub_size` to each circle, where the central circles have the highest
# over sampling factor and the outer circles have the lowest.

# The size of the circles that are appropriate for determining the over sampling factor are dependent on the resolution
# of the grid. For a high resolution grid (e.g. low pixel scale), a smaller circle central circle is necessary to
# over sample the profile accurately. The config file below therefore specifies the "radial factors" used for
# automatically determining the over sampling factors for each profile, which is the factor the pixel scale is multiplied
# by to determine the circle size.

# The config entry below defines the default over sampling factor for each profile, where:

# radial_factor_list: The factors that are multiplied by the pixel scale to determine the circle size that is used.
# sub_size_list: The over sampling factor that is used for each circle size.

# For the default entries below, oversampling of degree 32 x 32 is used within a circle of radius 3.01 x pixel scale,
# 4 x 4 within a circle of radius 10.01 x pixel scale and 2 x 2 for all pixels outside of this radius.

over_sampling:
  radial_factor_list:
    Chameleon: [1.0]
    ChameleonSph: [1.0]
    DevVaucouleurs: [1.0]
    DevVaucouleursSph: [1.0]
    dPIE: [1.0]
    dPIESph: [1.0]
    ExponentialRadialGradient: [1.0]
    ExponentialRadialGradientSph: [1.0]
    ElsonFreeFall: [1.0]
    ElsonFreeFallSph: [1.0]
    Exponential: [1.0]
    ExponentialCore: [1.0]
    ExponentialCoreSph: [1.0]
    ExponentialSph: [1.0]
    ExternalShear: [1.0]
    Gaussian: [1.0]
    GaussianSph: [1.0]
    gNFW: [1.0]
    gNFWMCRLudlow: [1.0]
    gNFWVirialMassConcSph: [1.0]
    gNFWSph: [1.0]
    Isothermal: [1.0]
    IsothermalCore: [1.0]
    IsothermalCoreSph: [1.0]
    IsothermalSph: [1.0]
    MassSheet: [1.0]
    Moffat: [1.0]
    MoffatSph: [1.0]
    PowerLawMultipole: [1.0]
    NFW: [1.0]
    NFWMCRDuffySph: [1.0]
    NFWMCRLudlow: [1.0]
    NFWMCRLudlowSph: [1.0]
    NFWMCRScatterLudlow: [1.0]
    NFWMCRScatterLudlowSph: [1.0]
    NFWVirialMassConcSph: [1.0]
    NFWSph: [1.0]
    NFWTruncatedMCRDuffySph: [1.0]
    NFWTruncatedMCRLudlowSph: [1.0]
    NFWTruncatedMCRScatterLudlowSph: [1.0]
    NFWTruncatedSph: [1.0]
    PointMass: [1.0]
    PowerLaw: [1.0]
    PowerLawBroken: [1.0]
    PowerLawBrokenSph: [1.0]
    PowerLawCore: [1.0]
    PowerLawCoreSph: [1.0]
    PowerLawSph: [1.0]
    Sersic: [1.0]
    SersicCore: [1.0]
    SersicCoreSph: [1.0]
    SersicRadialGradient: [1.0]
    SersicSph: [1.0]
    SersicRadialGradientSph: [1.0]
    ShapeletCartesianSph: [1.0]
    ShapeletCartesian: [1.0]
    ShapeletPolarSph: [1.0]
    ShapeletPolar: [1.0]
    ShapeletExponentialSph: [1.0]
    ShapeletExponential: [1.0]
    SMBH: [1.0]
    SMBHBinary: [1.0]
    EllProfile: [1.0]
    SersicAdaptTest: [0.1]
  sub_size_list:
    Chameleon: [1, 1]
    ChameleonSph: [1, 1]
    DevVaucouleurs: [1, 1]
    DevVaucouleursSph: [1, 1]
    dPIE: [1, 1]
    dPIESph: [1, 1]
    ExponentialRadialGradient: [1, 1]
    ExponentialRadialGradientSph: [1, 1]
    ElsonFreeFall: [1, 1]
    ElsonFreeFallSph: [1, 1]
    Exponential: [1, 1]
    ExponentialCore: [1, 1]
    ExponentialCoreSph: [1, 1]
    ExponentialSph: [1, 1]
    ExternalShear: [1, 1]
    Gaussian: [1, 1]
    GaussianSph: [1, 1]
    gNFW: [1, 1]
    gNFWMCRLudlow: [1, 1]
    gNFWVirialMassConcSph: [1, 1]
    gNFWSph: [1, 1]
    Isothermal: [1, 1]
    IsothermalCore: [1, 1]
    IsothermalCoreSph: [1, 1]
    IsothermalSph: [1, 1]
    MassSheet: [1, 1]
    Moffat: [1, 1]
    MoffatSph: [1, 1]
    PowerLawMultipole: [1, 1]
    NFW: [1, 1]
    NFWMCRDuffySph: [1, 1]
    NFWMCRLudlow: [1, 1]
    NFWMCRLudlowSph: [1, 1]
    NFWMCRScatterLudlow: [1, 1]
    NFWMCRScatterLudlowSph: [1, 1]
    NFWVirialMassConcSph : [1, 1]
    NFWSph: [1, 1]
    NFWTruncatedMCRDuffySph: [1, 1]
    NFWTruncatedMCRLudlowSph: [1, 1]
    NFWTruncatedMCRScatterLudlowSph: [1, 1]
    NFWTruncatedSph: [1, 1]
    PointMass: [1, 1]
    PowerLaw: [1, 1]
    PowerLawBroken: [1, 1]
    PowerLawBrokenSph: [1, 1]
    PowerLawCore: [1, 1]
    PowerLawCoreSph: [1, 1]
    PowerLawSph: [1, 1]
    Sersic: [1, 1]
    SersicCore: [1, 1]
    SersicCoreSph: [1, 1]
    SersicRadialGradient: [1, 1]
    SersicSph: [1, 1]
    SersicRadialGradientSph: [1, 1]
    ShapeletCartesianSph: [1, 1]
    ShapeletCartesian: [1, 1]
    ShapeletPolarSph: [1, 1]
    ShapeletPolar: [1, 1]
    ShapeletExponentialSph: [1, 1]
    ShapeletExponential: [1, 1]
    SMBH: [1, 1]
    SMBHBinary: [1, 1]
    EllProfile: [1, 1]
    SersicAdaptTest: [8, 1]