dPIE:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  ra:
    type: Uniform
    lower_limit: 0.0001
    upper_limit: 8.0
  rs:
    type: Uniform
    lower_limit: 0.01
    upper_limit: 100
  kappa_scale:
    type: Uniform
    lower_limit: 0.00001
    upper_limit: 1.0e8
  ell_comps_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
dPIESph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    lower_limit: -inf
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  ra:
    type: Uniform
    lower_limit: 0.0001
    upper_limit: 8.0
  rs:
    type: Uniform
    lower_limit: 0.01
    upper_limit: 100
  kappa_scale:
    type: Uniform
    lower_limit: 0.00001
    upper_limit: 1.0e8
